name: Weather Notification

on:
  schedule:
    - cron: '0 0 * * *'  # 每天晚上 12 点 UTC，相当于北京时间每天早上 8 点执行
  workflow_dispatch: 

jobs:
  send_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run weather script
        run: |
          chmod +x weather_push.sh 
          ./weather_push.sh  
        env:
          APP_ID: ${{ secrets.APP_ID }}  # 从 GitHub Secrets 获取 APP_ID
          APP_SECRET: ${{ secrets.APP_SECRET }}  # 从 GitHub Secrets 获取 APP_SECRET
          OPEN_ID: ${{ secrets.OPEN_ID }}  # 从 GitHub Secrets 获取 OPEN_ID
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}  # 从 GitHub Secrets 获取 TEMPLATE_ID
          CITY: ${{ secrets.CITY }}  # 从 GitHub Secrets 获取 CITY
